version: '3.4'

services:
    kmasasqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "kmas@Database"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
        container_name: kmasadatabase

    kmasabackend:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
        - "80"
        - "443"
        volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        container_name: kmasabackend
        depends_on:
            - kmasasqlserver
