version: '3.4'

services:
    kmasasqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"

    kmasabackend:
        image: ${DOCKER_REGISTRY-}kmasabackend
        build:
          context: .
          dockerfile: Core.API/Dockerfile