version: '3.8'

services:
    kmasasqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "kmas@Database"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
    kmasabackend:
        build:
            context: .
            dockerfile: Core.API/Dockerfile    
        depends_on:
            - kmasasqlserver
        ports:
            - "5000:5000"
        image: coreapi:latest
